apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
  labels:
    app: simpleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
      - name: simpleapp
        image: lfoltran/demoapp:1.0
        ports:
        - containerPort: 8008
        envFrom:
          - configMapRef:
              name: simpleapp-cm
